version: '3.8'

services:
    # App
    web1: 
        container_name: web1
        image: julenjus/gamepost_webapp:v0.4
        depends_on: 
            - mysql
            - rest
        links:
            - mysql
            - rest
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gamepost
    
    web2: 
        container_name: web2
        image: julenjus/gamepost_webapp:v0.0
        depends_on: 
            - mysql
            - rest
        links:
            - mysql
            - rest
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gamepost

    # MySQL
    mysql:
        container_name: mysql
        image: julenjus/gamepost_mysql:v0.3
        expose:
            - "3306"
        environment: 
            MYSQL_DATABASE: 'gamepost'
            MYSQL_ROOT_PASSWORD: 'pass'

    rest:
        container_name: rest
        image: julenjus/gamepost_rest_00_homebypreferences:v0.1
        expose:
            - "8081"
        depends_on: 
            - mysql
        links:
            - mysql
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gamepost

    lb:
        container_name: lb
        image: haproxy:1.9.6
        ports:
          - "80:80" # Only service that is exposed to the host is the lb 
          - "443:443"
        volumes:
          - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
        restart: always
